'''Ejercicio de la Clase 1'''
nombre = input("Ingrese el nombre del cliente: ")
apellido = input("Ingrese el apellido del cliente: ")
edad = input("Ingrese la edad del cliente: ")
mail = input("Ingrese el mail del cliente: ")
print("*"*11, end="\n")
print("* TARJETA *", end= "\n")
print("*"*11, end="\n")
print("Cliente: ", nombre + " " + apellido)
print("Edad: ", edad)
print("Mail: ", mail)